# Generated by Django 4.1.3 on 2022-11-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0002_saveimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveimage',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='saveimage',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
