# Generated by Django 4.1.3 on 2022-11-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0006_alter_saveimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='saveimage',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='saveimage',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='saveimage',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
