# Generated by Django 4.1.3 on 2022-11-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attend', '0007_saveimage_department_saveimage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namedate',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
